// Copyright (c) 2026 Erik Adelbert. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// mixergen generates mixer, sampler, and patch code variants.
// It is for internal use only. DO NOT INSTALL.
package main

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"iter"
	"os"
	"text/template"
)

//go:embed templates/*
var templateFS embed.FS

const (
	MixerFile       = "mixer.gen.go"
	SamplerFile     = "sampler.gen.go"
	PatchFile       = "patch.gen.go"
	MixerTemplate   = "mixer.go.tpl"
	SamplerTemplate = "sampler.go.tpl"
	PatchTemplate   = "patch.go.tpl"
	genHeader       = "//go:build !ignore_generated\n// Code generated by /cmd/mixergen; DO NOT EDIT.\n\n"
)

func main() {
	cfg := Config{
		Package:  "mixer",
		Variants: AllVariants(),
	}
	genMixers := mustTemplate("mixers", "templates/"+MixerTemplate)
	genSamplers := mustTemplate("samplers", "templates/"+SamplerTemplate)
	genPatch := mustTemplate("patch", "templates/"+PatchTemplate)

	writeGenerated(
		MixerFile,
		cfg.Package,
		mixerImports(),
		func(buf *bytes.Buffer) error {
			return genMixers.ExecuteTemplate(buf, MixerTemplate, cfg.Variants)
		},
	)
	writeGenerated(
		PatchFile,
		cfg.Package,
		patchImports(),
		func(buf *bytes.Buffer) error {
			return genPatch.ExecuteTemplate(buf, PatchTemplate, cfg.Variants)
		},
	)

	samplers := uniqueSamplers(cfg.Variants)

	writeGenerated(
		SamplerFile,
		cfg.Package,
		samplerImports(),
		func(buf *bytes.Buffer) error {
			return genSamplers.ExecuteTemplate(buf, SamplerTemplate, samplers)
		},
	)
}

/* ---------------- helpers ---------------- */

func mustTemplate(name string, files ...string) *template.Template {
	return template.Must(template.New(name).ParseFS(templateFS, files...))
}

func writeGenerated(
	filename, pkg string,
	imports []string,
	emit func(*bytes.Buffer) error,
) {
	var buf bytes.Buffer

	buf.WriteString(genHeader)
	buf.WriteString("// Code generated by /cmd/mixergen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)

	if len(imports) > 0 {
		writeImports(&buf, imports)
	}

	if err := emit(&buf); err != nil {
		panic(err)
	}

	src, err := format.Source(buf.Bytes())

	if err != nil {
		panic(err)
	}

	if err := os.WriteFile(filename, src, 0644); err != nil {
		panic(err)
	}
}

func writeImports(buf *bytes.Buffer, imports []string) {
	buf.WriteString("import (\n")

	for _, imp := range imports {
		fmt.Fprintf(buf, "\t%s\n", imp)
	}

	buf.WriteString(")\n\n")
}

func patchImports() []string {
	return []string{
		`ac "github.com/erik-adelbert/duh/internal/components/voice"`,
	}
}

func mixerImports() []string {
	return []string{
		`"iter"`,
		`ac "github.com/erik-adelbert/duh/internal/components/voice"`,
		`"github.com/erik-adelbert/duh/internal/components/sample"`,
	}
}

func samplerImports() []string {
	return []string{
		`"iter"`,
		`ac "github.com/erik-adelbert/duh/internal/components/voice"`,
	}
}

func uniqueSamplers(vars iter.Seq[Variant]) map[string]Variant {
	out := make(map[string]Variant)

	for v := range vars {
		out[v.Sampler] = v
	}

	return out
}
