.TH AACENC 1
.SH NAME
aacenc \- command-line tool
.SH SYNOPSIS
.B aacenc
.SH DESCRIPTION
Encode raw PCM audio data into AAC format
.SH SYNOPSIS
.B bin/aacenc [flags]
.SH OPTIONS
  -if string
    	input PCM format
  -o string
    	output AAC file (default: stdout) (default "-")
  -of string
    	output AAC format
  -v	Enable verbose output
