.TH MP3ENC 1
.SH NAME
mp3enc \- command-line tool
.SH SYNOPSIS
.B mp3enc
.SH DESCRIPTION
Encode raw PCM audio data into MP3 format
.SH SYNOPSIS
.B bin/mp3enc [flags]
.SH OPTIONS
  -if string
    	input PCM format
  -o string
    	output MP3 file (default: stdout) (default "-")
  -of string
    	output MP3 format
  -v	Enable verbose output
