.TH PCMCONV 1
.SH NAME
pcmconv \- command-line tool
.SH SYNOPSIS
.B pcmconv
.SH DESCRIPTION
Convert PCM data from one format to another
.SH SYNOPSIS
.B bin/pcmconv [flags]
.SH OPTIONS
  -if string
    	input format (s16c2r44100)
  -of string
    	output format (s24c2r44100)
  -v	Enable verbose output
