.TH PCMTUI 1
.SH NAME
pcmtui \- command-line tool
.SH SYNOPSIS
.B pcmtui
.SH DESCRIPTION
Play PCM audio data with visualizations
.SH SYNOPSIS
.B bin/pcmtui [flags]
.SH OPTIONS
  -emoji
    	if spectro then emoji mode
  -i string
    	path to MP3 file (default: stdin) (default "-")
  -if string
    	Input format (s16c2r44100)
  -p	Enable PCM passthrough mode
  -spectro
    	Display spectrogram
  -v	Enable verbose output
  -vu
    	Display VU bars
