.TH PPUNPACK 1
.SH NAME
ppunpack \- command-line tool
.SH SYNOPSIS
.B ppunpack
.SH DESCRIPTION
Decompress files compressed with the PP20 algorithm
.SH SYNOPSIS
.B bin/ppunpack [flags]
.SH OPTIONS
  -i string
    	Input file path
  -o string
    	Output file path (default "-")
  -v	Enable verbose output
