.TH UNMMCMP 1
.SH NAME
unmmcmp \- command-line tool
.SH SYNOPSIS
.B unmmcmp
.SH DESCRIPTION
Decompress files compressed with the MMCMP algorithm
.SH SYNOPSIS
.B bin/unmmcmp [flags]
.SH OPTIONS
  -i string
    	Input file path
  -o string
    	Output file path (default "-")
  -v	Enable verbose output
