.TH VGMTUI 1
.SH NAME
vgmtui \- command-line tool
.SH SYNOPSIS
.B vgmtui
.SH DESCRIPTION
Play VGM files with visualizations
.SH SYNOPSIS
.B bin/vgmtui [flags]
.SH OPTIONS
  -dump
    	Dump VGM commands to stdout and exit
  -f string
    	VGM file path
  -n int
    	Loop count (-1 for infinite) (default 2)
  -opl3
    	Display OPL3 registers
  -spectro
    	Display spectrogram
  -v	Enable verbose output
  -vu
    	Display vubars
