.TH VGMWAV 1
.SH NAME
vgmwav \- command-line tool
.SH SYNOPSIS
.B vgmwav
.SH DESCRIPTION
Convert VGM files to WAV format
.SH SYNOPSIS
.B bin/vgmwav [flags]
.SH OPTIONS
  -i string
    	input VGM file
  -n int
    	number of loops to play (min/default 1) (default 1)
  -o string
    	output WAV file (default "out.wav")
  -of string
    	output format (default "s16c2r44100")
  -v	Enable verbose output
