.TH WAVENC 1
.SH NAME
wavenc \- command-line tool
.SH SYNOPSIS
.B wavenc
.SH DESCRIPTION
Encode raw PCM audio data into WAV format
.SH SYNOPSIS
.B bin/wavenc [flags]
.SH OPTIONS
  -if string
    	input PCM format
  -o string
    	output WAV file (default: stdout) (default "-")
  -of string
    	output WAV format
  -v	Enable verbose output
