.TH WAVTUI 1
.SH NAME
wavtui \- command-line tool
.SH SYNOPSIS
.B wavtui
.SH DESCRIPTION
Play WAV files with a TUI player
.SH SYNOPSIS
.B bin/wavtui [flags]
.SH OPTIONS
  -emoji
    	if spectro then emoji mode
  -f string
    	path to the WAV file
  -spectro
    	enable spectro
  -v	Enable verbose output
  -vu
    	enable VU meter
