//go:build !ignore_generated

// Code generated by /cmd/mixergen; DO NOT EDIT.

package mixer

import (
	"iter"

	"github.com/erik-adelbert/duh/internal/tracker/components/sample"
	ac "github.com/erik-adelbert/duh/internal/tracker/components/voice"
)

// NearestMonoMixer8 mixes mono 8-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func NearestMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllNearestMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// NearestMonoMixer16 mixes mono 16-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func NearestMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllNearestMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// NearestFastMonoMixer8 mixes mono 8-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func NearestFastMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllNearestMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Right
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// NearestFastMonoMixer16 mixes mono 16-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func NearestFastMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllNearestMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Right
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// NearestStereoMixer8 mixes stereo 8-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func NearestStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllNearestStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// NearestStereoMixer16 mixes stereo 16-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func NearestStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllNearestStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// NearestRampMonoMixer8 mixes mono 8-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func NearestRampMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllNearestMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// NearestRampMonoMixer16 mixes mono 16-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func NearestRampMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllNearestMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// NearestRampFastMonoMixer8 mixes mono 8-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func NearestRampFastMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Right
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllNearestMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Right
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// NearestRampFastMonoMixer16 mixes mono 16-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func NearestRampFastMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Right
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllNearestMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Right
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// NearestRampStereoMixer8 mixes stereo 8-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func NearestRampStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllNearestStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// NearestRampStereoMixer16 mixes stereo 16-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func NearestRampStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllNearestStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterNearestMonoMixer8 mixes mono 8-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FilterNearestMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFilterNearestMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FilterNearestMonoMixer16 mixes mono 16-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FilterNearestMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFilterNearestMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FilterNearestStereoMixer8 mixes stereo 8-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func FilterNearestStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllFilterNearestStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// FilterNearestStereoMixer16 mixes stereo 16-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func FilterNearestStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllFilterNearestStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// FilterNearestRampMonoMixer8 mixes mono 8-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FilterNearestRampMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFilterNearestMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterNearestRampMonoMixer16 mixes mono 16-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FilterNearestRampMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFilterNearestMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterNearestRampStereoMixer8 mixes stereo 8-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func FilterNearestRampStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllFilterNearestStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterNearestRampStereoMixer16 mixes stereo 16-bit PCM samples using nearest interpolation.
// This function applies nearest interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func FilterNearestRampStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllFilterNearestStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// LinearMonoMixer8 mixes mono 8-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func LinearMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllLinearMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// LinearMonoMixer16 mixes mono 16-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func LinearMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllLinearMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// LinearFastMonoMixer8 mixes mono 8-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func LinearFastMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllLinearMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Right
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// LinearFastMonoMixer16 mixes mono 16-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func LinearFastMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllLinearMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Right
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// LinearStereoMixer8 mixes stereo 8-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func LinearStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllLinearStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// LinearStereoMixer16 mixes stereo 16-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func LinearStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllLinearStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// LinearRampMonoMixer8 mixes mono 8-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func LinearRampMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllLinearMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// LinearRampMonoMixer16 mixes mono 16-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func LinearRampMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllLinearMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// LinearRampFastMonoMixer8 mixes mono 8-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func LinearRampFastMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Right
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllLinearMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Right
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// LinearRampFastMonoMixer16 mixes mono 16-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func LinearRampFastMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Right
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllLinearMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Right
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// LinearRampStereoMixer8 mixes stereo 8-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func LinearRampStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllLinearStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// LinearRampStereoMixer16 mixes stereo 16-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func LinearRampStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllLinearStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterLinearMonoMixer8 mixes mono 8-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FilterLinearMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFilterLinearMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FilterLinearMonoMixer16 mixes mono 16-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FilterLinearMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFilterLinearMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FilterLinearStereoMixer8 mixes stereo 8-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func FilterLinearStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllFilterLinearStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// FilterLinearStereoMixer16 mixes stereo 16-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func FilterLinearStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllFilterLinearStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// FilterLinearRampMonoMixer8 mixes mono 8-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FilterLinearRampMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFilterLinearMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterLinearRampMonoMixer16 mixes mono 16-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FilterLinearRampMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFilterLinearMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterLinearRampStereoMixer8 mixes stereo 8-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func FilterLinearRampStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllFilterLinearStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterLinearRampStereoMixer16 mixes stereo 16-bit PCM samples using linear interpolation.
// This function applies linear interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func FilterLinearRampStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllFilterLinearStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// SplineMonoMixer8 mixes mono 8-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func SplineMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllSplineMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// SplineMonoMixer16 mixes mono 16-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func SplineMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllSplineMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// SplineFastMonoMixer8 mixes mono 8-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func SplineFastMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllSplineMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Right
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// SplineFastMonoMixer16 mixes mono 16-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func SplineFastMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllSplineMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Right
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// SplineStereoMixer8 mixes stereo 8-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func SplineStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllSplineStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// SplineStereoMixer16 mixes stereo 16-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func SplineStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllSplineStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// SplineRampMonoMixer8 mixes mono 8-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func SplineRampMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllSplineMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// SplineRampMonoMixer16 mixes mono 16-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func SplineRampMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllSplineMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// SplineRampFastMonoMixer8 mixes mono 8-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func SplineRampFastMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Right
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllSplineMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Right
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// SplineRampFastMonoMixer16 mixes mono 16-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func SplineRampFastMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Right
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllSplineMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Right
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// SplineRampStereoMixer8 mixes stereo 8-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func SplineRampStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllSplineStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// SplineRampStereoMixer16 mixes stereo 16-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func SplineRampStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllSplineStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterSplineMonoMixer8 mixes mono 8-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FilterSplineMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFilterSplineMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FilterSplineMonoMixer16 mixes mono 16-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FilterSplineMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFilterSplineMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FilterSplineStereoMixer8 mixes stereo 8-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func FilterSplineStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllFilterSplineStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// FilterSplineStereoMixer16 mixes stereo 16-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func FilterSplineStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllFilterSplineStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// FilterSplineRampMonoMixer8 mixes mono 8-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FilterSplineRampMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFilterSplineMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterSplineRampMonoMixer16 mixes mono 16-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FilterSplineRampMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFilterSplineMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterSplineRampStereoMixer8 mixes stereo 8-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func FilterSplineRampStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllFilterSplineStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterSplineRampStereoMixer16 mixes stereo 16-bit PCM samples using spline interpolation.
// This function applies spline interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func FilterSplineRampStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllFilterSplineStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FIRMonoMixer8 mixes mono 8-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FIRMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFIRMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FIRMonoMixer16 mixes mono 16-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FIRMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFIRMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FIRFastMonoMixer8 mixes mono 8-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FIRFastMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFIRMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Right
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FIRFastMonoMixer16 mixes mono 16-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FIRFastMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFIRMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Right
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FIRStereoMixer8 mixes stereo 8-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func FIRStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllFIRStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// FIRStereoMixer16 mixes stereo 16-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func FIRStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllFIRStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// FIRRampMonoMixer8 mixes mono 8-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FIRRampMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFIRMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FIRRampMonoMixer16 mixes mono 16-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FIRRampMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFIRMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FIRRampFastMonoMixer8 mixes mono 8-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FIRRampFastMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Right
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFIRMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Right
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FIRRampFastMonoMixer16 mixes mono 16-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FIRRampFastMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Right
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFIRMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Right
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FIRRampStereoMixer8 mixes stereo 8-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func FIRRampStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllFIRStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FIRRampStereoMixer16 mixes stereo 16-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func FIRRampStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllFIRStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterFIRMonoMixer8 mixes mono 8-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FilterFIRMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFilterFIRMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FilterFIRMonoMixer16 mixes mono 16-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FilterFIRMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull(AllFilterFIRMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += c * gain.Volume.Left
		mixbuf[i+1] += c * gain.Volume.Right
	}
}

// FilterFIRStereoMixer8 mixes stereo 8-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func FilterFIRStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllFilterFIRStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// FilterFIRStereoMixer16 mixes stereo 16-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func FilterFIRStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	next, stop := iter.Pull2(AllFilterFIRStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		mixbuf[i] += l * gain.Volume.Left
		mixbuf[i+1] += r * gain.Volume.Right
	}
}

// FilterFIRRampMonoMixer8 mixes mono 8-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit mono PCM data.
func FilterFIRRampMonoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFilterFIRMonoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterFIRRampMonoMixer16 mixes mono 16-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit mono PCM data.
func FilterFIRRampMonoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull(AllFilterFIRMonoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		c, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += c * rL
		mixbuf[i+1] += c * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterFIRRampStereoMixer8 mixes stereo 8-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 8-bit stereo PCM data.
func FilterFIRRampStereoMixer8(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllFilterFIRStereoSamples8(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}

// FilterFIRRampStereoMixer16 mixes stereo 16-bit PCM samples using FIR interpolation.
// This function applies FIR interpolation to the input samples in src,
// mixes the result into the output buffer buf, and applies per-channel gain.
// It assumes buf is large enough to hold the output and that data contains
// valid 16-bit stereo PCM data.
func FilterFIRRampStereoMixer16(mixbuf []Fp284, cue *ac.Cue, gain *ac.Gain, filter *ac.Filter, data sample.Data, flags ac.Flags) {
	i := cue.FPart

	if flags&ac.VoiceStereo != 0 {
		i *= 2
	}

	rL := gain.Ramp.Left
	rR := gain.Ramp.Right

	next, stop := iter.Pull2(AllFilterFIRStereoSamples16(data[i:], cue, filter))

	defer stop()

	for i := 0; i < len(mixbuf); i += 2 {
		l, r, ok := next()

		if !ok {
			break
		}

		rL += gain.Volume.Left
		rR += gain.Volume.Right

		mixbuf[i] += l * rL
		mixbuf[i+1] += r * rR
	}

	gain.Ramp.Left = rL
	gain.Left = rL >> 12
	gain.Ramp.Right = rR
	gain.Right = rR >> 12
}
