//go:build !ignore_generated

// Code generated by /cmd/mixergen; DO NOT EDIT.

package mixer

import (
	ac "github.com/erik-adelbert/duh/internal/tracker/components/voice"
	"iter"
)

// AllFIRMonoSamples16 yields mono 16-bit samples using FIR interpolation.
// This function reads from buf, applies FIR interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFIRMonoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		step := 2 * cue.Step
		bufLen := len(buf)/2 - wfWidth + 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - wfFracBits)

			var l, r Fp284
			j0 := int(frac * wfWidth)

			for j := range wfWidth {
				k := Fp284(wfLUT[j0+j])

				l += k * (Fp284(buf[(idx+j)*2]) | Fp284(buf[(idx+j)*2+1])<<8)
			}

			l >>= wfShift16
			_ = r // generation sugar for mono

			if !yield(l) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFIRMonoSamples8 yields mono 8-bit samples using FIR interpolation.
// This function reads from buf, applies FIR interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFIRMonoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		step := cue.Step
		bufLen := len(buf) - wfWidth + 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - wfFracBits)

			var l, r Fp284
			j0 := int(frac * wfWidth)

			for j := range wfWidth {
				k := Fp284(wfLUT[j0+j])

				l += k * Fp284(buf[idx+j])
			}

			l >>= wfShift16
			_ = r // generation sugar for mono

			if !yield(l) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFIRStereoSamples16 yields stereo 16-bit samples using FIR interpolation.
// This function reads from buf, applies FIR interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFIRStereoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		step := 4 * cue.Step
		bufLen := len(buf)/4 - wfWidth + 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - wfFracBits)

			var l, r Fp284
			j0 := int(frac * wfWidth)

			for j := range wfWidth {
				k := Fp284(wfLUT[j0+j])

				l += k * (Fp284(buf[(idx+j)*4]) | Fp284(buf[(idx+j)*4+1])<<8)
				r += k * (Fp284(buf[(idx+j)*4+2]) | Fp284(buf[(idx+j)*4+3])<<8)
			}

			l >>= wfShift16

			if !yield(l, r) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFIRStereoSamples8 yields stereo 8-bit samples using FIR interpolation.
// This function reads from buf, applies FIR interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFIRStereoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		step := 2 * cue.Step
		bufLen := len(buf)/2 - wfWidth + 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - wfFracBits)

			var l, r Fp284
			j0 := int(frac * wfWidth)

			for j := range wfWidth {
				k := Fp284(wfLUT[j0+j])

				l += k * Fp284(buf[(idx+j)*2])
				r += k * Fp284(buf[(idx+j)*2+1])
			}

			l >>= wfShift16

			if !yield(l, r) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterFIRMonoSamples16 yields mono 16-bit samples using FIR interpolation.
// This function reads from buf, applies FIR interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterFIRMonoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 2 * cue.Step
		bufLen := len(buf)/2 - wfWidth + 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - wfFracBits)

			var l, r Fp284
			j0 := int(frac * wfWidth)

			for j := range wfWidth {
				k := Fp284(wfLUT[j0+j])

				l += k * (Fp284(buf[(idx+j)*2]) | Fp284(buf[(idx+j)*2+1])<<8)
			}

			l >>= wfShift16
			_ = r // generation sugar for mono

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterFIRMonoSamples8 yields mono 8-bit samples using FIR interpolation.
// This function reads from buf, applies FIR interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterFIRMonoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := cue.Step
		bufLen := len(buf) - wfWidth + 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - wfFracBits)

			var l, r Fp284
			j0 := int(frac * wfWidth)

			for j := range wfWidth {
				k := Fp284(wfLUT[j0+j])

				l += k * Fp284(buf[idx+j])
			}

			l >>= wfShift16
			_ = r // generation sugar for mono

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterFIRStereoSamples16 yields stereo 16-bit samples using FIR interpolation.
// This function reads from buf, applies FIR interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterFIRStereoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 4 * cue.Step
		bufLen := len(buf)/4 - wfWidth + 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - wfFracBits)

			var l, r Fp284
			j0 := int(frac * wfWidth)

			for j := range wfWidth {
				k := Fp284(wfLUT[j0+j])

				l += k * (Fp284(buf[(idx+j)*4]) | Fp284(buf[(idx+j)*4+1])<<8)
				r += k * (Fp284(buf[(idx+j)*4+2]) | Fp284(buf[(idx+j)*4+3])<<8)
			}

			l >>= wfShift16

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l, r) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterFIRStereoSamples8 yields stereo 8-bit samples using FIR interpolation.
// This function reads from buf, applies FIR interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterFIRStereoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 2 * cue.Step
		bufLen := len(buf)/2 - wfWidth + 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - wfFracBits)

			var l, r Fp284
			j0 := int(frac * wfWidth)

			for j := range wfWidth {
				k := Fp284(wfLUT[j0+j])

				l += k * Fp284(buf[(idx+j)*2])
				r += k * Fp284(buf[(idx+j)*2+1])
			}

			l >>= wfShift16

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l, r) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterLinearMonoSamples16 yields mono 16-bit samples using linear interpolation.
// This function reads from buf, applies linear interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterLinearMonoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 2 * cue.Step
		bufLen := len(buf)/2 - 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i)

			l0 := Fp284(buf[idx*2]) | Fp284(buf[idx*2+1])<<8
			l1 := Fp284(buf[idx*2+2]) | Fp284(buf[idx*2+3])<<8
			r0, r1 := Fp284(0), Fp284(0)

			l := l0 + ((l1-l0)*frac)>>16
			r := r0 + ((r1-r0)*frac)>>16
			_ = r // generation sugar for mono

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterLinearMonoSamples8 yields mono 8-bit samples using linear interpolation.
// This function reads from buf, applies linear interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterLinearMonoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := cue.Step
		bufLen := len(buf) - 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i)

			l0 := Fp284(buf[idx]) << 8
			l1 := Fp284(buf[idx+1]) << 8
			r0, r1 := Fp284(0), Fp284(0)

			l := l0 + ((l1-l0)*frac)>>16
			r := r0 + ((r1-r0)*frac)>>16
			_ = r // generation sugar for mono

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterLinearStereoSamples16 yields stereo 16-bit samples using linear interpolation.
// This function reads from buf, applies linear interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterLinearStereoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 4 * cue.Step
		bufLen := len(buf)/4 - 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i)

			l0 := Fp284(buf[idx*4]) | Fp284(buf[idx*4+1])<<8
			l1 := Fp284(buf[idx*4+4]) | Fp284(buf[idx*4+5])<<8
			r0 := Fp284(buf[idx*4+2]) | Fp284(buf[idx*4+3])<<8
			r1 := Fp284(buf[idx*4+6]) | Fp284(buf[idx*4+7])<<8

			l := l0 + ((l1-l0)*frac)>>16
			r := r0 + ((r1-r0)*frac)>>16
			_ = r // generation sugar for mono

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l, r) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterLinearStereoSamples8 yields stereo 8-bit samples using linear interpolation.
// This function reads from buf, applies linear interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterLinearStereoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 2 * cue.Step
		bufLen := len(buf)/2 - 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i)

			l0 := Fp284(buf[idx*2]) << 8
			l1 := Fp284(buf[idx*2+2]) << 8
			r0 := Fp284(buf[idx*2+1]) << 8
			r1 := Fp284(buf[idx*2+3]) << 8

			l := l0 + ((l1-l0)*frac)>>16
			r := r0 + ((r1-r0)*frac)>>16
			_ = r // generation sugar for mono

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l, r) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterNearestMonoSamples16 yields mono 16-bit samples using nearest interpolation.
// This function reads from buf, applies nearest interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterNearestMonoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 2 * cue.Step
		bufLen := len(buf) / 2

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)

			l := Fp284(buf[idx*2]) | Fp284(buf[idx*2+1])<<8
			r := Fp284(0)
			_ = r // generation sugar for mono

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterNearestMonoSamples8 yields mono 8-bit samples using nearest interpolation.
// This function reads from buf, applies nearest interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterNearestMonoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := cue.Step
		bufLen := len(buf)

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)

			l := Fp284(buf[idx]) << 8
			r := Fp284(0)
			_ = r // generation sugar for mono

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterNearestStereoSamples16 yields stereo 16-bit samples using nearest interpolation.
// This function reads from buf, applies nearest interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterNearestStereoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 4 * cue.Step
		bufLen := len(buf) / 4

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)

			l := Fp284(buf[idx*4]) | Fp284(buf[idx*4+1])<<8
			r := Fp284(buf[idx*4+2]) | Fp284(buf[idx*4+3])<<8

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l, r) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterNearestStereoSamples8 yields stereo 8-bit samples using nearest interpolation.
// This function reads from buf, applies nearest interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterNearestStereoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 2 * cue.Step
		bufLen := len(buf) / 2

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)

			l := Fp284(buf[idx*2]) << 8
			r := Fp284(buf[idx*2+1]) << 8

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l, r) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterSplineMonoSamples16 yields mono 16-bit samples using spline interpolation.
// This function reads from buf, applies spline interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterSplineMonoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 2 * cue.Step
		bufLen := len(buf)/2 - 3

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - csFracBits)

			var l, r Fp284

			for j := range 4 {
				j0 := int(frac)*4 + j
				cs := Fp284(csLUT[j0])

				l += cs * (Fp284(buf[(idx+j)*2]) | Fp284(buf[(idx+j)*2+1])<<8)
				r = 0
			}

			l >>= csShift16
			_ = r // generation sugar for mono

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterSplineMonoSamples8 yields mono 8-bit samples using spline interpolation.
// This function reads from buf, applies spline interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterSplineMonoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := cue.Step
		bufLen := len(buf) - 3

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - csFracBits)

			var l, r Fp284

			for j := range 4 {
				j0 := int(frac)*4 + j
				cs := Fp284(csLUT[j0])

				l += cs * (Fp284(buf[idx+j]) << 8)
				r = 0
			}

			l >>= csShift16
			_ = r // generation sugar for mono

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterSplineStereoSamples16 yields stereo 16-bit samples using spline interpolation.
// This function reads from buf, applies spline interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterSplineStereoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 4 * cue.Step
		bufLen := len(buf)/4 - 3

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - csFracBits)

			var l, r Fp284

			for j := range 4 {
				j0 := int(frac)*4 + j
				cs := Fp284(csLUT[j0])

				l += cs * (Fp284(buf[(idx+j)*4]) | Fp284(buf[(idx+j)*4+1])<<8)
				r += cs * (Fp284(buf[(idx+j)*4+2]) | Fp284(buf[(idx+j)*4+3])<<8)
			}

			l >>= csShift16

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l, r) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllFilterSplineStereoSamples8 yields stereo 8-bit samples using spline interpolation.
// This function reads from buf, applies spline interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllFilterSplineStereoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		A0, B0, B1 := filter.A0, filter.B0, filter.B1
		y1, y2 := filter.Y[0], filter.Y[1]
		y3, y4 := filter.Y[2], filter.Y[3]

		step := 2 * cue.Step
		bufLen := len(buf)/2 - 3

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - csFracBits)

			var l, r Fp284

			for j := range 4 {
				j0 := int(frac)*4 + j
				cs := Fp284(csLUT[j0])

				l += cs * (Fp284(buf[(idx+j)*2]) << 8)
				r += cs * (Fp284(buf[(idx+j)*2+1]) << 8)
			}

			l >>= csShift16

			l = (l*A0 + y1*B0 + y2*B1 + 4096) >> 13
			r = (r*A0 + y3*B0 + y4*B1 + 4096) >> 13

			y2, y1 = y1, l
			y4, y3 = y3, r

			if !yield(l, r) {
				break
			}
		}

		filter.Y = [4]Fp284{y1, y2, y3, y4}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllLinearMonoSamples16 yields mono 16-bit samples using linear interpolation.
// This function reads from buf, applies linear interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllLinearMonoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		step := 2 * cue.Step
		bufLen := len(buf)/2 - 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i)

			l0 := Fp284(buf[idx*2]) | Fp284(buf[idx*2+1])<<8
			l1 := Fp284(buf[idx*2+2]) | Fp284(buf[idx*2+3])<<8
			r0, r1 := Fp284(0), Fp284(0)

			l := l0 + ((l1-l0)*frac)>>16
			r := r0 + ((r1-r0)*frac)>>16
			_ = r // generation sugar for mono

			if !yield(l) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllLinearMonoSamples8 yields mono 8-bit samples using linear interpolation.
// This function reads from buf, applies linear interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllLinearMonoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		step := cue.Step
		bufLen := len(buf) - 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i)

			l0 := Fp284(buf[idx]) << 8
			l1 := Fp284(buf[idx+1]) << 8
			r0, r1 := Fp284(0), Fp284(0)

			l := l0 + ((l1-l0)*frac)>>16
			r := r0 + ((r1-r0)*frac)>>16
			_ = r // generation sugar for mono

			if !yield(l) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllLinearStereoSamples16 yields stereo 16-bit samples using linear interpolation.
// This function reads from buf, applies linear interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllLinearStereoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		step := 4 * cue.Step
		bufLen := len(buf)/4 - 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i)

			l0 := Fp284(buf[idx*4]) | Fp284(buf[idx*4+1])<<8
			l1 := Fp284(buf[idx*4+4]) | Fp284(buf[idx*4+5])<<8
			r0 := Fp284(buf[idx*4+2]) | Fp284(buf[idx*4+3])<<8
			r1 := Fp284(buf[idx*4+6]) | Fp284(buf[idx*4+7])<<8

			l := l0 + ((l1-l0)*frac)>>16
			r := r0 + ((r1-r0)*frac)>>16
			_ = r // generation sugar for mono

			if !yield(l, r) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllLinearStereoSamples8 yields stereo 8-bit samples using linear interpolation.
// This function reads from buf, applies linear interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllLinearStereoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		step := 2 * cue.Step
		bufLen := len(buf)/2 - 1

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i)

			l0 := Fp284(buf[idx*2]) << 8
			l1 := Fp284(buf[idx*2+2]) << 8
			r0 := Fp284(buf[idx*2+1]) << 8
			r1 := Fp284(buf[idx*2+3]) << 8

			l := l0 + ((l1-l0)*frac)>>16
			r := r0 + ((r1-r0)*frac)>>16
			_ = r // generation sugar for mono

			if !yield(l, r) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllNearestMonoSamples16 yields mono 16-bit samples using nearest interpolation.
// This function reads from buf, applies nearest interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllNearestMonoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		step := 2 * cue.Step
		bufLen := len(buf) / 2

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)

			l := Fp284(buf[idx*2]) | Fp284(buf[idx*2+1])<<8
			r := Fp284(0)
			_ = r // generation sugar for mono

			if !yield(l) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllNearestMonoSamples8 yields mono 8-bit samples using nearest interpolation.
// This function reads from buf, applies nearest interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllNearestMonoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		step := cue.Step
		bufLen := len(buf)

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)

			l := Fp284(buf[idx]) << 8
			r := Fp284(0)
			_ = r // generation sugar for mono

			if !yield(l) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllNearestStereoSamples16 yields stereo 16-bit samples using nearest interpolation.
// This function reads from buf, applies nearest interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllNearestStereoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		step := 4 * cue.Step
		bufLen := len(buf) / 4

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)

			l := Fp284(buf[idx*4]) | Fp284(buf[idx*4+1])<<8
			r := Fp284(buf[idx*4+2]) | Fp284(buf[idx*4+3])<<8

			if !yield(l, r) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllNearestStereoSamples8 yields stereo 8-bit samples using nearest interpolation.
// This function reads from buf, applies nearest interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllNearestStereoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		step := 2 * cue.Step
		bufLen := len(buf) / 2

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)

			l := Fp284(buf[idx*2]) << 8
			r := Fp284(buf[idx*2+1]) << 8

			if !yield(l, r) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllSplineMonoSamples16 yields mono 16-bit samples using spline interpolation.
// This function reads from buf, applies spline interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllSplineMonoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		step := 2 * cue.Step
		bufLen := len(buf)/2 - 3

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - csFracBits)

			var l, r Fp284

			for j := range 4 {
				j0 := int(frac)*4 + j
				cs := Fp284(csLUT[j0])

				l += cs * (Fp284(buf[(idx+j)*2]) | Fp284(buf[(idx+j)*2+1])<<8)
				r = 0
			}

			l >>= csShift16
			_ = r // generation sugar for mono

			if !yield(l) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllSplineMonoSamples8 yields mono 8-bit samples using spline interpolation.
// This function reads from buf, applies spline interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit mono PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllSplineMonoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq[Fp284] {
	return func(yield func(Fp284) bool) {
		var i int32

		step := cue.Step
		bufLen := len(buf) - 3

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - csFracBits)

			var l, r Fp284

			for j := range 4 {
				j0 := int(frac)*4 + j
				cs := Fp284(csLUT[j0])

				l += cs * (Fp284(buf[idx+j]) << 8)
				r = 0
			}

			l >>= csShift16
			_ = r // generation sugar for mono

			if !yield(l) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllSplineStereoSamples16 yields stereo 16-bit samples using spline interpolation.
// This function reads from buf, applies spline interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 16-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllSplineStereoSamples16(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		step := 4 * cue.Step
		bufLen := len(buf)/4 - 3

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - csFracBits)

			var l, r Fp284

			for j := range 4 {
				j0 := int(frac)*4 + j
				cs := Fp284(csLUT[j0])

				l += cs * (Fp284(buf[(idx+j)*4]) | Fp284(buf[(idx+j)*4+1])<<8)
				r += cs * (Fp284(buf[(idx+j)*4+2]) | Fp284(buf[(idx+j)*4+3])<<8)
			}

			l >>= csShift16

			if !yield(l, r) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

// AllSplineStereoSamples8 yields stereo 8-bit samples using spline interpolation.
// This function reads from buf, applies spline interpolation (and filtering if applicable),
// and yields the resulting sample(s) as Fp284 values. The cue is updated with the new playback position.
// The function assumes buf contains valid 8-bit stereo PCM data and is large enough
// for the requested operation.
// It returns an iterator (Seq or Seq2) yielding one (mono) or two (stereo) Fp284 samples per call.
func AllSplineStereoSamples8(buf []int8, cue *ac.Cue, filter *ac.Filter) iter.Seq2[Fp284, Fp284] {
	return func(yield func(Fp284, Fp284) bool) {
		var i int32

		step := 2 * cue.Step
		bufLen := len(buf)/2 - 3

		for i = cue.FPart; hi(i) < bufLen; i += step {
			idx := hi(i)
			frac := lo(i) >> (16 - csFracBits)

			var l, r Fp284

			for j := range 4 {
				j0 := int(frac)*4 + j
				cs := Fp284(csLUT[j0])

				l += cs * (Fp284(buf[(idx+j)*2]) << 8)
				r += cs * (Fp284(buf[(idx+j)*2+1]) << 8)
			}

			l >>= csShift16

			if !yield(l, r) {
				break
			}
		}

		cue.IPart = int32(hi(i))
		cue.FPart = int32(lo(i))
	}
}

func hi(i int32) int { return int(i >> 16) }

func lo(i int32) Fp284 { return Fp284(i & 0xFFFF) }
